CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                             NOT NULL UNIQUE,
    password   VARCHAR(255)                             NOT NULL,
    name       VARCHAR(255)                             NOT NULL,
    role       VARCHAR(255)                             NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                             NOT NULL,
    user_id    INTEGER                                  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE                 NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT fk_categories_on_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE budgets
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value       DECIMAL(11, 2)                           NOT NULL,
    month       INTEGER                                  NOT NULL,
    year        INTEGER                                  NOT NULL,
    user_id     INTEGER                                  NOT NULL,
    category_id INTEGER                                  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                 NOT NULL,
    CONSTRAINT pk_budgets PRIMARY KEY (id),
    CONSTRAINT fk_budgets_on_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_budgets_on_category
        FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    CONSTRAINT uq_budget_user_category_month_year
        UNIQUE (user_id, category_id, month, year)
);

CREATE TABLE expenses
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value       DECIMAL(11, 2)                           NOT NULL,
    description VARCHAR(255),
    user_id     INTEGER                                  NOT NULL,
    category_id INTEGER                                  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                 NOT NULL,
    CONSTRAINT pk_expenses PRIMARY KEY (id),
    CONSTRAINT fk_expenses_on_category
        FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    CONSTRAINT fk_expenses_on_user
        FOREIGN KEY (user_id) references users(id) ON DELETE CASCADE
);